/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2016-06-02 16:22:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.issue;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class issue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/include/header.jspf", Long.valueOf(1464232031000L));
    _jspx_dependants.put("/include/navigation.jspf", Long.valueOf(1464763368000L));
    _jspx_dependants.put("file:/Users/Songhee/.m2/repository/org/springframework/spring-webmvc/4.2.5.RELEASE/spring-webmvc-4.2.5.RELEASE.jar", Long.valueOf(1459995762000L));
    _jspx_dependants.put("jar:file:/Users/Songhee/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("file:/Users/Songhee/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1441966472000L));
    _jspx_dependants.put("jar:file:/Users/Songhee/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/include/tags.jspf", Long.valueOf(1464232308000L));
    _jspx_dependants.put("jar:file:/Users/Songhee/.m2/repository/org/springframework/spring-webmvc/4.2.5.RELEASE/spring-webmvc-4.2.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1456330292000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"kr\">\n");
      out.write("<head>\n");
      out.write("\t");
      out.write("\n");
      out.write("<!-- <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"> -->\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\n");
      out.write("<title>Issue Tracking System</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.3/dialog-polyfill.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://code.getmdl.io/1.1.3/material.blue_grey-orange.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/styles.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/tinymce.css\">");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"issues issues--wrap mdl-layout mdl-js-layout has-drawer is-upgraded\">\n");
      out.write("      <!-- <header class=\"mdl-layout__header mdl-layout__header--waterfall\">\n");
      out.write("        <div class=\"mdl-layout__header-row\">\n");
      out.write("          Title\n");
      out.write("          <span class=\"mdl-layout-title\">javajigi/slipp</span>\n");
      out.write("        </div>\n");
      out.write("        Tabs\n");
      out.write("        <div class=\"mdl-layout__tab-bar mdl-js-ripple-effect\">\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp\"\" class=\"mdl-layout__tab\">Code</a>\n");
      out.write("          <a href=\"#\" class=\"mdl-layout__tab is-active\">\n");
      out.write("            <span class=\"mdl-badge\" data-badge=\"11\">Issues</span>\n");
      out.write("          </a>\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp/pulls\" class=\"mdl-layout__tab\">\n");
      out.write("            <span class=\"mdl-badge\" data-badge=\"0\">Pull requests</span>\n");
      out.write("          </a>\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp/wiki\" class=\"mdl-layout__tab\">Wiki</a>\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp/pulse\" class=\"mdl-layout__tab\">Pulse</a>\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp/graphs\" class=\"mdl-layout__tab\">Graphs</a>\n");
      out.write("        </div>\n");
      out.write("      </header> -->\n");
      out.write("      ");
      out.write("\n");
      out.write("<header class=\"mdl-layout__header mdl-layout__header--waterfall\">\n");
      out.write("\t<div class=\"mdl-layout__header-row\">\n");
      out.write("\t\t<!-- Title -->\n");
      out.write("\t\t<span class=\"mdl-layout-title\"><a href=\"/\" >IssueManager</a></span>\n");
      out.write("\t\t<div class=\"mdl-layout-title loginbox\">\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Tabs -->\n");
      out.write("\t<div class=\"mdl-layout__tab-bar mdl-js-ripple-effect\">\n");
      out.write("\t\t<a href=\"https://github.com/javajigi/slipp\" \" class=\"mdl-layout__tab\">Code</a>\n");
      out.write("\t\t<a href=\"#\" class=\"mdl-layout__tab is-active\"> <span\n");
      out.write("\t\t\tclass=\"mdl-badge\" data-badge=\"11\">Issues</span>\n");
      out.write("\t\t</a> <a href=\"https://github.com/javajigi/slipp/pulls\"\n");
      out.write("\t\t\tclass=\"mdl-layout__tab\"> \n");
      out.write("\t\t\t<span class=\"mdl-badge\" data-badge=\"0\">Pull requests</span>\n");
      out.write("\t\t</a> <a href=\"https://github.com/javajigi/slipp/wiki\"\n");
      out.write("\t\t\tclass=\"mdl-layout__tab\">Wiki</a> <a\n");
      out.write("\t\t\thref=\"https://github.com/javajigi/slipp/pulse\"\n");
      out.write("\t\t\tclass=\"mdl-layout__tab\">Pulse</a> <a\n");
      out.write("\t\t\thref=\"https://github.com/javajigi/slipp/graphs\"\n");
      out.write("\t\t\tclass=\"mdl-layout__tab\">Graphs</a>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</header>\n");
      out.write("<div class=\"mdl-layout__drawer\">\n");
      out.write("\t<span class=\"mdl-layout-title\">GitHub</span>\n");
      out.write("</div>");
      out.write("\n");
      out.write("      <div class=\"mdl-layout__drawer\">\n");
      out.write("        <span class=\"mdl-layout-title\">GitHub</span>\n");
      out.write("      </div>\n");
      out.write("      <main class=\"mdl-layout__content\">\n");
      out.write("        <div class=\"issues-back\">\n");
      out.write("          <a class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\" href=\"/projects/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" title=\"go back\" role=\"button\">\n");
      out.write("            <i class=\"material-icons\" role=\"presentation\">arrow_back</i>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"issues__posts mdl-grid\">\n");
      out.write("          <div class=\"mdl-card mdl-shadow--4dp mdl-cell mdl-cell--12-col\">\n");
      out.write("            <div class=\"mdl-card__menu\">\n");
      out.write("              <button class=\"mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect\">\n");
      out.write("                <i class=\"material-icons\">edit</i>\n");
      out.write("              </button>\n");
      out.write("              <button id=\"issues-menu-lower-right\" class=\"mdl-button mdl-js-button mdl-button--icon\">\n");
      out.write("                <i class=\"material-icons\">more_vert</i>\n");
      out.write("              </button>\n");
      out.write("              <ul class=\"mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect mdl-color-text--grey-700\" for=\"issues-menu-lower-right\">\n");
      out.write("                <li class=\"mdl-menu__item--full-bleed-divider\"><strong>Labels</strong></li>\n");
      out.write("                <li class=\"mdl-menu__item\">enhancement</li>\n");
      out.write("                <li class=\"mdl-menu__item--full-bleed-divider\"><strong>Milestone</strong></li>\n");
      out.write("                <li class=\"mdl-menu__item\">No milestone</li>\n");
      out.write("                <li class=\"mdl-menu__item--full-bleed-divider\"><strong>Assignee</strong></li>\n");
      out.write("                <li class=\"mdl-menu__item\">javajigi</li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mdl-card__title mdl-color-text--grey-50\">\n");
      out.write("              <i class=\"material-icons\">check_circle</i>\n");
      out.write("              <h2 class=\"mdl-card__title-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${issue.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('#');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${issue.issueId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mdl-color-text--grey-700 mdl-card__supporting-text meta\">\n");
      out.write("              <a href=\"https://github.com/javajigi\">\n");
      out.write("                <img class=\"minilogo\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("              </a>\n");
      out.write("              <div>\n");
      out.write("                <div class=\"author-text\">\n");
      out.write("                  <strong>\n");
      out.write("                    <a href=\"#\" class=\"author\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${issue.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                  </strong>\n");
      out.write("                </div>\n");
      out.write("                <!-- <span>11 Aug 2015</span> -->\n");
      out.write("              </div>\n");
      out.write("              <div class=\"section-spacer\"></div>\n");
      out.write("            <!--   <button class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("                <i class=\"material-icons\" role=\"presentation\">thumb_up</i><span class=\"visuallyhidden\">like comment</span>\n");
      out.write("              </button>\n");
      out.write("              <button class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("                <i class=\"material-icons\" role=\"presentation\">thumb_down</i><span class=\"visuallyhidden\">dislike comment</span>\n");
      out.write("              </button> -->\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mdl-color-text--grey-700 mdl-card__supporting-text\">\n");
      out.write("              <!-- <p>현재 모든 설정 파일도 java config 기반으로 변경했다.<br>spring boot 기반으로 설정을 변경하는 것도 가능하겠다.</p> -->\n");
      out.write("              <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${issue.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mdl-color-text--primary-contrast mdl-card__supporting-text comments\">\n");
      out.write("              <!-- comments start -->\n");
      out.write("             <!--  <div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("                <header class=\"comment__header\">\n");
      out.write("                  <img class=\"comment__avatar2\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                  <div class=\"comment__author\">\n");
      out.write("                    <strong>\n");
      out.write("                      <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("                      <span>added the enhancement label on 11 Aug 2015</span>\n");
      out.write("                    </strong>\n");
      out.write("                  </div>\n");
      out.write("                </header>\n");
      out.write("              </div>\n");
      out.write("              <hr> -->\n");
      out.write("              <!-- <div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("                <header class=\"comment__header\">\n");
      out.write("                  <img class=\"comment__avatar2\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                  <div class=\"comment__author\">\n");
      out.write("                    <strong>\n");
      out.write("                      <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("                      <span>self-assigned this on 11 Aug 2015</span>\n");
      out.write("                    </strong>\n");
      out.write("                  </div>\n");
      out.write("                </header>\n");
      out.write("              </div>\n");
      out.write("              <hr> -->\n");
      out.write("              <!-- <div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("                <header class=\"comment__header\">\n");
      out.write("                  <img class=\"comment__avatar2\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                  <div class=\"comment__author\">\n");
      out.write("                    <strong>\n");
      out.write("                      <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("                      <span>added this to the 반복주기 15 milestone on 11 Aug 2015</span>\n");
      out.write("                    </strong>\n");
      out.write("                  </div>\n");
      out.write("                </header>\n");
      out.write("              </div>\n");
      out.write("              <hr> -->\n");
      out.write("              <div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("                <header class=\"comment__header\">\n");
      out.write("                  <img class=\"comment__avatar\" height=\"48\" width=\"48\" src=\"#\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${issue.user_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                  <div class=\"comment__author\">\n");
      out.write("                    <strong>\n");
      out.write("                      <a href=\"#\" class=\"author\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${issue.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                    </strong>\n");
      out.write("                  </div>\n");
      out.write("                  <nav class=\"comment__actions\">\n");
      out.write("                  </nav>\n");
      out.write("                </header>\n");
      out.write("                <div class=\"comment__text\">\n");
      out.write("                  <span>모든 소스 코드를 scala 기반으로 변경한 후에 진행하는 것이 좋을 수도 있겠다.</span>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <hr>\n");
      out.write("              \n");
      out.write("             <!--  <div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("                <header class=\"comment__header\">\n");
      out.write("                  <img class=\"comment__avatar2\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                  <div class=\"comment__author\">\n");
      out.write("                    <strong>\n");
      out.write("                      <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("                      <span>removed this from the 반복주기 15 milestone on 11 Aug 2015</span>\n");
      out.write("                    </strong>\n");
      out.write("                  </div>\n");
      out.write("                </header>\n");
      out.write("              </div>\n");
      out.write("              <hr>\n");
      out.write("              <div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("                <header class=\"comment__header\">\n");
      out.write("                  <img class=\"comment__avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                  <div class=\"comment__author\">\n");
      out.write("                    <strong>\n");
      out.write("                      <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("                    </strong>\n");
      out.write("                    <span>17 Dec 2015</span>\n");
      out.write("                  </div>\n");
      out.write("                  <nav class=\"comment__actions\">\n");
      out.write("                    <button class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("                      <i class=\"material-icons\" role=\"presentation\">thumb_up</i><span class=\"visuallyhidden\">like comment</span>\n");
      out.write("                    </button>\n");
      out.write("                    <button class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("                      <i class=\"material-icons\" role=\"presentation\">thumb_down</i><span class=\"visuallyhidden\">dislike comment</span>\n");
      out.write("                    </button>\n");
      out.write("                  </nav>\n");
      out.write("                </header>\n");
      out.write("                <div class=\"comment__text\">\n");
      out.write("                  <span>시도했으나 과정이 너무 복잡함. 이후에 다시 진행하는 것이 좋겠음.</span>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <hr>\n");
      out.write("              <div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("                <header class=\"comment__header\">\n");
      out.write("                  <img class=\"comment__avatar2\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                  <div class=\"comment__author\">\n");
      out.write("                    <strong>\n");
      out.write("                      <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("                      <span>closed this on 17 Dec 2015</span>\n");
      out.write("                    </strong>\n");
      out.write("                  </div>\n");
      out.write("                </header>\n");
      out.write("              </div> -->\n");
      out.write("            </div>\n");
      out.write("              <!-- comments end -->\n");
      out.write("            <div class=\"mdl-color-text--primary-contrast mdl-card__supporting-text new-comment\">\n");
      out.write("              <form>\n");
      out.write("                <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\n");
      out.write("                  <textarea rows=5 class=\"mdl-textfield__input\" id=\"comment\"></textarea>\n");
      out.write("                  <label for=\"comment\" class=\"mdl-textfield__label\">Leave a comment</label>\n");
      out.write("                </div>\n");
      out.write("                <button class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("                  <i class=\"material-icons\" role=\"presentation\">check</i><span class=\"visuallyhidden\">add comment</span>\n");
      out.write("                </button>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <footer class=\"mdl-mini-footer\">\n");
      out.write("          <div class=\"mdl-mini-footer--left-section\">\n");
      out.write("            <div class=\"mdl-logo mdl-color-text--grey-600\">Proudly powered by <a href=\"https://github.com/Byeol\">Byeol</a></div>\n");
      out.write("          </div>\n");
      out.write("        </footer>\n");
      out.write("      </main>\n");
      out.write("      <div class=\"mdl-layout__obfuscator\"></div>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"https://code.getmdl.io/1.1.3/material.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t        ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /include/navigation.jspf(9,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t        \t<span class =mdl-layout-title\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\n");
        out.write("\t        \t<span class =mdl-layout-title\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("님 환영해요!</span>\n");
        out.write("\t\t        <span class =mdl-layout-title\"><a href=\"/users/logout\" role=\"button\">Log out</a></span>\n");
        out.write("\t\t        <span class =mdl-layout-title\"><a href=\"/users/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/\" role=\"button\">setting</a></span>\n");
        out.write("\t        ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t<span class =mdl-layout-title\"> <a href=\"/users/join\" role=\"button\">Join</a></span>\n");
        out.write("\t\t\t\t<span class =mdl-layout-title\"> <a href=\"/users/login\" role=\"button\">Login</a></span>\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
