/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M4
 * Generated at: 2016-05-23 06:37:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\n");
      out.write("    <title>Issue Tracking System</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.3/dialog-polyfill.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.1.3/material.blue_grey-orange.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/styles.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/tinymce.css\">\n");
      out.write("</head>\n");
      out.write("  <body>\n");
      out.write("    <div class=\"issues issues--wrap mdl-layout mdl-js-layout has-drawer is-upgraded\">\n");
      out.write("      <header class=\"mdl-layout__header mdl-layout__header--waterfall\">\n");
      out.write("        <div class=\"mdl-layout__header-row\">\n");
      out.write("          <!-- Title -->\n");
      out.write("          <span class=\"mdl-layout-title\">IssueManager</span>\n");
      out.write("        </div>\n");
      out.write("        <!-- Tabs -->\n");
      out.write("        <div class=\"mdl-layout__tab-bar mdl-js-ripple-effect\">\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp\"\" class=\"mdl-layout__tab\">Code</a>\n");
      out.write("          <a href=\"#\" class=\"mdl-layout__tab is-active\">\n");
      out.write("            <span class=\"mdl-badge\" data-badge=\"11\">Issues</span>\n");
      out.write("          </a>\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp/pulls\" class=\"mdl-layout__tab\">\n");
      out.write("            <span class=\"mdl-badge\" data-badge=\"0\">Pull requests</span>\n");
      out.write("          </a>\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp/wiki\" class=\"mdl-layout__tab\">Wiki</a>\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp/pulse\" class=\"mdl-layout__tab\">Pulse</a>\n");
      out.write("          <a href=\"https://github.com/javajigi/slipp/graphs\" class=\"mdl-layout__tab\">Graphs</a>\n");
      out.write("        </div>\n");
      out.write("      </header>\n");
      out.write("      <div class=\"mdl-layout__drawer\">\n");
      out.write("        <span class=\"mdl-layout-title\">GitHub</span>\n");
      out.write("      </div>\n");
      out.write("      <main class=\"mdl-layout__content\">\n");
      out.write("        <div class=\"issues__posts mdl-grid\">\n");
      out.write("          <div class=\"issues-card-wide mdl-card mdl-shadow--2dp\">\n");
      out.write("            <div class=\"mdl-card__title mdl-shadow--2dp\">\n");
      out.write("              <h2 class=\"mdl-card__title-text mdl-color-text--grey-800\">Open Issues</h2>\n");
      out.write("            </div>\n");
      out.write("            <button class=\"mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored show-modal\">\n");
      out.write("              <i class=\"material-icons\">add</i>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"mdl-card__supporting-text\">\n");
      out.write("              <ul class=\"issue-list mdl-list\">\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>spring boot로 전환 작업 진행해 본다.</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"0\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>질문 간에 답변을 이동할 수 있어야 한다.</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"0\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>페이스북의 경우 댓글의 댓글을 가져올 수 있도록 한다.</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"0\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>[버그] 화면 스크롤 시 오른쪽 \"태그추가\" 버튼 크기 자동 변경</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"3\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>사용자가 수정을 하는 경우 수정된 시간이 반영되지 않는다.</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"0\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>본인이 누른 좋아요와 싫어요를 인지할 수 있도록 한다.</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"1\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>페북 로그인 사용자의 경우 페북에 바로 댓글 달 수 있도록 한다.</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"0\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>질문 작성 중 임시저장 기능이 있으면 좋겠어요</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"1\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>원 글에도 공감하기를 할 수 있도록 한다.</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"5\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>자신이 공감한 글을 볼 수 있도록 해주세요</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"4\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"mdl-list__item mdl-list__item--two-line\">\n");
      out.write("                  <span class=\"mdl-list__item-primary-content\">\n");
      out.write("                    <a href=\"https://github.com/javajigi\">\n");
      out.write("                      <img class=\"mdl-list__item-avatar\" height=\"48\" width=\"48\" src=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\" alt=\"@javajigi\">\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"issue.html\"><strong>트랙백이 가능하도록 한다.</strong></a>\n");
      out.write("                    <span class=\"mdl-list__item-sub-title\">#259 opened <relative-time datetime=\"2016-01-12T08:08:59Z\" title=\"2016년 1월 12일 오후 5:08 GMT+9\">on 12 Jan</relative-time> by <a href=\"https://github.com/javajigi/slipp/issues?q=is%3Aissue+is%3Aopen+author%3Ajavajigi\" aria-label=\"View all issues opened by javajigi\" class=\"tooltipped tooltipped-s muted-link\">javajigi</a></span>\n");
      out.write("                    </span>\n");
      out.write("                  </span>\n");
      out.write("                  <span class=\"mdl-list__item-secondary-content\">\n");
      out.write("                    <div class=\"material-icons mdl-badge mdl-badge--overlap\" data-badge=\"0\">comment</div>\n");
      out.write("                  </span>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <footer class=\"mdl-mini-footer\">\n");
      out.write("          <div class=\"mdl-mini-footer--left-section\">\n");
      out.write("            <div class=\"mdl-logo mdl-color-text--grey-600\">Proudly powered by <a href=\"https://github.com/Byeol\">Byeol</a></div>\n");
      out.write("          </div>\n");
      out.write("        </footer>\n");
      out.write("      </main>\n");
      out.write("      <div class=\"mdl-layout__obfuscator\"></div>\n");
      out.write("    </div>\n");
      out.write("    <dialog class=\"mdl-dialog new-issue\">\n");
      out.write("      <div class=\"pr\">\n");
      out.write("        <i class=\"material-icons\">create</i>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"mdl-dialog__content\">\n");
      out.write("        <form action=\"#\">\n");
      out.write("          <div class=\"mdl-textfield mdl-js-textfield\">\n");
      out.write("            <input class=\"mdl-textfield__input\" type=\"text\" id=\"new-issue__title\">\n");
      out.write("            <label class=\"mdl-textfield__label\" for=\"new-issue__title\"><strong>Title</strong></label>\n");
      out.write("          </div>\n");
      out.write("          <textarea rows=20 class=\"mdl-textfield__input\" id=\"new-issue__comment\"></textarea>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"mdl-dialog__actions mdl-dialog__actions\">\n");
      out.write("        <button type=\"button\" class=\"mdl-button close\">Submit new issue</button>\n");
      out.write("      </div>\n");
      out.write("    </dialog>\n");
      out.write("    <script src=\"https://code.getmdl.io/1.1.3/material.min.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.3/dialog-polyfill.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.tinymce.com/4/tinymce.min.js\"></script>\n");
      out.write("    <script src=\"/resources/js/main.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
